#!/usr/bin/env python3
"""
predict_v2.py

Updated propaganda predictor that uses per-label calibrated thresholds
instead of a single fixed 0.5 threshold for all techniques.

Thresholds are loaded from per_label_thresholds.json (generated by debertaL_v2.py).
If not found, falls back to 0.5 for all labels.

RoRA adapters are loaded from rora_adapters.pt — critical for correct predictions.
"""

import torch
import json
import math
import os
import re
import numpy as np
from pathlib import Path
from transformers import AutoTokenizer, AutoModelForSequenceClassification

try:
    from nltk.tokenize import sent_tokenize
    import nltk
    try:
        nltk.data.find('tokenizers/punkt_tab')
    except LookupError:
        try:
            nltk.data.find('tokenizers/punkt')
        except LookupError:
            try:
                nltk.download('punkt_tab', quiet=True)
            except Exception:
                nltk.download('punkt', quiet=True)
except ImportError:
    import subprocess
    subprocess.check_call(['pip', 'install', 'nltk', '--break-system-packages'])
    from nltk.tokenize import sent_tokenize
    import nltk
    try:
        nltk.download('punkt_tab', quiet=True)
    except Exception:
        nltk.download('punkt', quiet=True)

MODEL_DIR = "./deberta-propaganda-multilabel_rora_rora"

# ===================== RoRA ADAPTER CLASSES =====================

class RoRALinear(torch.nn.Module):
    """
    LoRA wrapper with RoRA scaling (alpha / sqrt(rank)).
    Must match the architecture used during training in debertaL_v2.py.
    """
    def __init__(self, linear, rank, alpha, dropout=0.1):
        super().__init__()
        self.in_features  = linear.in_features
        self.out_features = linear.out_features
        self.rank  = rank
        self.scale = alpha / math.sqrt(rank)
        self.weight = linear.weight
        self.bias   = linear.bias
        self.lora_A = torch.nn.Parameter(torch.zeros(rank, linear.in_features))
        self.lora_B = torch.nn.Parameter(torch.zeros(linear.out_features, rank))
        self.dropout = torch.nn.Dropout(dropout)

    def forward(self, x):
        base = torch.nn.functional.linear(x, self.weight, self.bias)
        return base + self.dropout(x) @ self.lora_A.T @ self.lora_B.T * self.scale


def inject_rora(model, rank=32, alpha=64, dropout=0.1,
                target_layers=list(range(12, 24)),
                target_modules=["query_proj", "key_proj", "value_proj", "dense"]):
    """Inject RoRA adapter modules into the model — must be called before loading adapter weights."""
    for layer_idx in target_layers:
        layer = model.deberta.encoder.layer[layer_idx]
        for mod_name in target_modules:
            for submod_name, submod in [
                ("attention.self", layer.attention.self),
                ("attention.output", layer.attention.output),
                ("intermediate", layer.intermediate),
                ("output", layer),
            ]:
                if hasattr(submod, mod_name):
                    original = getattr(submod, mod_name)
                    if isinstance(original, torch.nn.Linear):
                        setattr(submod, mod_name,
                                RoRALinear(original, rank, alpha, dropout).to(original.weight.device))


# ===================== LOAD MODEL =====================
print("[INFO] Loading model...")

if not os.path.exists(MODEL_DIR):
    print(f"[ERROR] Model directory {MODEL_DIR} not found!")
    print("[INFO] Train the model first: python debertaL_v2.py --phase finetune")
    exit(1)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR)
model.to(device)

# Load RoRA adapter weights — critical, without this the backbone runs without
# the fine-tuned adapters and predictions will be inaccurate
rora_path = Path(MODEL_DIR) / "rora_adapters.pt"
if rora_path.exists():
    inject_rora(model)
    state = torch.load(rora_path, map_location=device)
    missing, unexpected = model.load_state_dict(state, strict=False)
    adapter_keys = [k for k in state if "lora" in k]
    print(f"[INFO] Loaded {len(adapter_keys)} RoRA adapter tensors from {rora_path}")
else:
    print(f"[WARNING] rora_adapters.pt not found at {rora_path}")
    print(f"          Predictions will be less accurate without adapter weights.")

model.eval()

# Load label mapping
label_file = os.path.join(MODEL_DIR, "label_mapping.json")
with open(label_file) as f:
    label_mapping = {int(k): v for k, v in json.load(f).items()}


threshold_file = os.path.join(MODEL_DIR, "per_label_thresholds.json")
if os.path.exists(threshold_file):
    with open(threshold_file) as f:
        per_label_thresholds = json.load(f)
    print(f"[INFO] Loaded calibrated per-label thresholds from {threshold_file}")
else:
    per_label_thresholds = {v: 0.5 for v in label_mapping.values()}
    print(f"[WARNING] No calibrated thresholds found. Using 0.5 for all labels.")

print(f"[INFO] Model loaded on {device}")
print(f"[INFO] Detecting {len(label_mapping)} propaganda techniques")


# ===================== EVIDENCE EXTRACTION =====================

LABEL_EVIDENCE_PATTERNS = {
    "appeal_to_authority": [
        r"(?:experts?|scientists?|doctors?|researchers?|officials?|leaders?|professors?)",
        r"according to",
        r"(?:study|studies|report|reports|research)",
        r"(?:warn|warned|say|says|said|agree|agrees|agreed|confirm|confirmed|prove|proves|proved)",
    ],
    "appeal_to_fear_prejudice": [
        r"(?:fear|threat|danger|dangerous|terror|terrorists?|invad(?:e|ed|ing)|destroy|catastrophe|crisis|too late)",
        r"(?:criminals?|illegals?|traitors?|enemy|enemies)",
    ],
    "bandwagon_reductio_ad_hitlerum": [
        r"(?:everyone|everybody|millions|all of us|the whole world|join the movement|join the winning team)",
        r"(?:hitler|nazi|nazis)",
    ],
    "black_and_white_fallacy": [
        r"(?:either|only|no middle ground|there is no alternative|with us or against us|must choose)",
        r"(?:always|never|completely|entirely)",
    ],
    "causal_oversimplification": [
        r"(?:because of|caused by|the reason is|that is why|due to)",
        r"(?:single cause|sole cause|one reason|only reason)",
    ],
    "doubt": [
        r"(?:lying|lie|lies|fake|hoax|can't trust|cannot trust|corrupt|cover[- ]?up|nobody knows|questionable|suspicious)",
    ],
    "exaggeration_minimisation": [
        r"(?:everyone|nobody|always|never|completely|totally|absolutely|nothing|everything|irreversible|end civilization)",
    ],
    "flag_waving": [
        r"(?:patriot|patriots?|traitor|nation|country|our troops|freedom|ancestors)",
    ],
    "loaded_language": [
        r"(?:criminals?|terrorists?|destroy|lying|traitor|catastrophe|invaded|corrupt|disaster|evil|shocking|outrageous)",
    ],
    "name_calling_labeling": [
        r"(?:traitor|criminals?|terrorists?|liar|liars|corrupt|enemy|enemies|radical|extremist)",
    ],
    "repetition": [
        r"(\w+)(?:\W+){1,}",
    ],
    "slogans": [
        r"(?:make .* great again|wake up|join the movement|take back control|fight for freedom)",
    ],
    "thought_terminating_cliches": [
        r"(?:it is what it is|end of story|case closed|everyone knows|do your own research|wake up|common sense)",
    ],
    "whataboutism_straw_men_red_herring": [
        r"(?:what about|how about|meanwhile|instead of addressing|the real issue is)",
        r"(?:so you're saying|they want you to believe)",
    ],
}


def _clean_snippet(snippet: str) -> str:
    return re.sub(r"\s+", " ", snippet).strip(" .,;:-")


def _find_pattern_snippets(text: str, patterns: list[str], limit: int = 3) -> list[str]:
    snippets = []
    seen = set()
    for pattern in patterns:
        for m in re.finditer(pattern, text, flags=re.IGNORECASE):
            snippet = _clean_snippet(m.group(0))
            if snippet and snippet.lower() not in seen:
                snippets.append(snippet)
                seen.add(snippet.lower())
            if len(snippets) >= limit:
                return snippets
    return snippets


def _extract_evidence_bullets(label: str, label_idx: int, sentence_details: list[dict], threshold: float,
                              max_bullets: int = 3) -> list[str]:
    patterns = LABEL_EVIDENCE_PATTERNS.get(label, [])
    if not sentence_details:
        return []

    ranked = sorted(
        sentence_details,
        key=lambda x: float(x["probs"][label_idx]),
        reverse=True,
    )

    bullets = []
    seen = set()
    sentence_gate = max(0.30, threshold * 0.65)

    for item in ranked:
        sent = item["text"].strip()
        sent_prob = float(item["probs"][label_idx])
        if sent_prob < sentence_gate:
            continue

        for snippet in _find_pattern_snippets(sent, patterns, limit=max_bullets):
            bullet = f'"{snippet}" in: "{_clean_snippet(sent)[:160]}"'
            if bullet not in seen:
                bullets.append(bullet)
                seen.add(bullet)
            if len(bullets) >= max_bullets:
                return bullets

    if bullets:
        return bullets

    top_sent = ranked[0]["text"].strip()
    if top_sent:
        return [f'Highest-contributing sentence: "{_clean_snippet(top_sent)[:180]}"']
    return []


# ===================== PREDICTION FUNCTION =====================

def predict_propaganda(text: str, verbose: bool = True, aggregation: str = "max") -> dict:
    """
    Analyze text for propaganda techniques.

    Uses per-label calibrated thresholds for more precise detection.
    For texts with 3+ sentences, analyzes hierarchically.

    Args:
        text: Input text to analyze
        verbose: Print formatted results
        aggregation: "max", "mean", or "weighted" for multi-sentence aggregation

    Returns:
        dict with keys: is_propaganda, num_techniques, techniques, all_scores
    """
    sentences = sent_tokenize(text)

    if len(sentences) <= 2:
        return _predict_single(text, verbose=verbose)

    if verbose:
        print(f"[INFO] Analyzing {len(sentences)} sentences ({aggregation} aggregation)...")

    all_probs = []
    kept_sentences = []
    for sent in sentences:
        if len(sent.split()) < 4:
            continue
        inputs = tokenizer(
            sent, return_tensors="pt",
            truncation=True, padding=True, max_length=512
        )
        inputs = {k: v.to(device) for k, v in inputs.items()}
        with torch.no_grad():
            probs = torch.sigmoid(model(**inputs).logits).cpu().numpy()[0]
        all_probs.append(probs)
        kept_sentences.append(sent)

    if not all_probs:
        return _predict_single(text, verbose=verbose)

    all_probs = np.array(all_probs)

    if aggregation == "max":
        agg_probs = np.max(all_probs, axis=0)
    elif aggregation == "mean":
        agg_probs = np.mean(all_probs, axis=0)
    elif aggregation == "weighted":
        weights = np.linspace(0.5, 1.0, len(all_probs))
        agg_probs = np.average(all_probs, axis=0, weights=weights)
    else:
        agg_probs = np.max(all_probs, axis=0)

    sentence_details = [
        {"text": sent, "probs": probs}
        for sent, probs in zip(kept_sentences, all_probs)
    ]

    return _build_result(
        agg_probs, text, verbose,
        header="PROPAGANDA ANALYSIS (HIERARCHICAL)",
        extra_info=f"Analyzed: {len(all_probs)} sentences",
        sentence_details=sentence_details,
    )


def _predict_single(text: str, verbose: bool = True) -> dict:
    """Predict on a single text chunk."""
    inputs = tokenizer(
        text, return_tensors="pt",
        truncation=True, padding=True, max_length=512
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}
    with torch.no_grad():
        probs = torch.sigmoid(model(**inputs).logits).cpu().numpy()[0]

    return _build_result(
        probs, text, verbose, header="PROPAGANDA ANALYSIS",
        sentence_details=[{"text": text, "probs": probs}],
    )


def _build_result(probs: np.ndarray, text: str, verbose: bool,
                  header: str = "PROPAGANDA ANALYSIS", extra_info: str = "",
                  sentence_details: list[dict] | None = None) -> dict:
    """Build result dict from probabilities using per-label thresholds."""
    detected_techniques = []
    all_scores = {}

    for idx, prob in enumerate(probs):
        technique = label_mapping[idx]
        threshold = per_label_thresholds.get(technique, 0.5)
        all_scores[technique] = float(prob)

        if prob >= threshold:
            evidence = _extract_evidence_bullets(
                technique, idx, sentence_details or [], threshold
            )
            detected_techniques.append({
                "technique": technique,
                "confidence": float(prob),
                "threshold": threshold,
                "evidence": evidence,
            })

    detected_techniques.sort(key=lambda x: x["confidence"], reverse=True)

    if verbose:
        print(header)
        print(f"Text: {text[:200]}{'...' if len(text) > 200 else ''}")
        if extra_info:
            print(extra_info)
        print("\n" + "-" * 60)

        if detected_techniques:
            print(f"PROPAGANDA DETECTED: {len(detected_techniques)} technique(s)\n")
            for item in detected_techniques:
                name = item["technique"].replace("_", " ").title()
                pct = item["confidence"] * 100
                t_pct = item["threshold"] * 100
                bar = "#" * int(pct / 5) + "-" * (20 - int(pct / 5))
                print(f"  {name:.<40} {pct:>5.1f}% {bar}  [thresh: {t_pct:.0f}%]")
                for bullet in item.get("evidence", []):
                    print(f"     - {bullet}")
        else:
            print("NO propaganda techniques detected above calibrated thresholds")
            sorted_scores = sorted(all_scores.items(), key=lambda x: x[1], reverse=True)
            print(f"\nTop scoring techniques (below threshold):")
            for technique, score in sorted_scores[:5]:
                name = technique.replace("_", " ").title()
                t = per_label_thresholds.get(technique, 0.5) * 100
                print(f"  {name:.<40} {score*100:>5.1f}%  [thresh: {t:.0f}%]")

        print("=" * 60 + "\n")

    return {
        "is_propaganda": len(detected_techniques) > 0,
        "num_techniques": len(detected_techniques),
        "techniques": detected_techniques,
        "all_scores": all_scores,
    }


# ===================== EXAMPLE USAGE =====================
if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("PROPAGANDA DETECTION v2 — CALIBRATED THRESHOLDS")
    print("=" * 60)

    test_texts = [
        "Our country is being invaded by criminals and terrorists who want to destroy everything our ancestors built. True patriots must stand up now before it's too late.",
        "The mainstream media is lying to you about everything. Wake up, they control what you see, what you think, and who you vote for. Do your own research.",
        "Either you support our troops completely or you are a traitor to this nation. There is no middle ground when it comes to defending our freedom.",
        "Studies suggest that immigration has contributed to rising crime rates in several urban areas, according to concerned community leaders.",
        "Everyone is switching to our party because they know the other side has failed this country for decades. Join the winning team.",
        "Scientists have repeatedly warned us that we are heading toward an irreversible climate catastrophe that will end civilization as we know it.",
        "The city council voted 6-3 to approve the new budget, which allocates additional funding for road repairs and public transit.",
        "Researchers at Johns Hopkins published a study examining the relationship between sleep duration and cognitive performance in adults over 60.",
        "The vaccines were rushed through approval and nobody knows the long term effects. Thousands of doctors are speaking out but nobody is listening.",
        "Our product is used by millions of satisfied customers worldwide. Join the movement and experience the difference everyone is talking about.",
    ]

    for i, text in enumerate(test_texts, 1):
        print(f"\n{'='*60}")
        print(f"TEST {i}/{len(test_texts)}")
        predict_propaganda(text)

    print("\n[INFO] Analysis complete!")
